# Example sensor monitoring definitions

groups: #be able to compose a path /xyz/openbmc_project/sensors/[type]/[member]
    - name: core_temp_group
      description: Group of core temp sensors
      type: temperature #path in sensors namespace
      members: #sensor name(s) to be in group
          - core0
          - core1
          - core2
          - core3

triggers:
    - name: app_start
      description: The sensor group manager application started
      type: start
    - name: properties_changed
      description: A property change dbus signal
      type: dbus #instance of a class
      signature: #constructor inputs
          interface: org.freedesktop.DBus.Properties
          member: PropertiesChanged

conditions:
    - name: number_of_cores_at_or_above_temp
      type: number_in_group
      interface: xyz.openbmc_project.Sensor.Value
      property: value
      count: 3
      op: >=
      value:
          value: 115
          type: uint32

actions:
    - name: log_error
      type: log_error
    - name: shutdown
      type: shutdown

events: #dictionary(map, vector, or...)
    - name: cores_overtemp
      groups:
          - core_temp_group
      triggers:
          - name: app_start
            conditions:
                - too_many_zone_members_hot
          - name: properties_changed
            conditions:
                - number_of_cores_at_or_above_temp
      actions:
          - name: log_error
          - name: shutdown
